version: "3.0"

services:
  convert-adoc:
    image: quirinecker/asciidoctor-convert
    container_name: convert-adoc
    build: .
    environment:
      - CONVERT_SLIDES=true
    volumes:
      - ./input/:/app/input
      - ./output/:/app/output
