version: "3.0"

services:
  convert-adoc:
    image: docker.pkg.github.com/quirinecker/asciidoctor-convert-action/docker-image:latest
    container_name: convert-adoc
    build: .
    environment:
      - CONVERT_SLIDES=true
    volumes:
      - ./input/:/app/input
      - ./output/:/app/output
