name: asciidoctor github pages

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Build ⚙
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker-compose build
      - name: Login Docker Registry
        run: docker login ghcr.io --username actions-user --password-stdin
      - name: Push Docker Image
        run: docker-compose push
