name: testing the asciidoc convert action

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Build ⚙
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: ./.github/actions/asciidoctor-convert
        with:
          slides: false
          inputPath: input
          outputPath: output
      - name: Commit & Push changes
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ github.token }}
          directory: output
