name: testing the asciidoc convert action

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Build ⚙
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: ./.github/actions/asciidoctor-convert
        with:
          slides: false
          inputPath: input
          outputPath: output
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: ./output
          force: true
